// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfo9cqhRF8FufZE5jK4QYfvtSbUUJdNSU',
    appId: '1:375333230289:web:1a0f67b686ba404eef97f0',
    messagingSenderId: '375333230289',
    projectId: 'thebrandsapp-fc8ae',
    authDomain: 'thebrandsapp-fc8ae.firebaseapp.com',
    storageBucket: 'thebrandsapp-fc8ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOVYvm5bAKGoXqYQoGxKZGS_EPyLYKs_0',
    appId: '1:375333230289:android:2fe75882fcf4a635ef97f0',
    messagingSenderId: '375333230289',
    projectId: 'thebrandsapp-fc8ae',
    storageBucket: 'thebrandsapp-fc8ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9KL7m-xAVV12O80bjnChMJ4Ex_2vyAEc',
    appId: '1:375333230289:ios:f79b818c9e39d324ef97f0',
    messagingSenderId: '375333230289',
    projectId: 'thebrandsapp-fc8ae',
    storageBucket: 'thebrandsapp-fc8ae.appspot.com',
    iosBundleId: 'com.example.thebrandsapp',
  );
}
